# version: '3.9'

services:
  my_mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 0
      MYSQL_DATABASE: customdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 0
      TZ: Asia/Seoul
    # volumes:
    #   - ./db/mysql/data:/var/lib/mysql
    #   - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  
  nginx_react:
    container_name: nginx_react
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - springboot

  flask:
    container_name: flask
    # 환경 설정 부분
    env_file:
      - ./AI/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_HOST=my_mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=0
      - DATABASE_NAME=customdb
    build:
      context: ./AI
      dockerfile: Dockerfile
    volumes:
      - ./AI:/AI
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - celery
      - redis
      - my_mysql

  celery:
    container_name: celery_service
    env_file:
      - ./AI/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build:
      context: ./AI/RVC_custom
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./AI:/AI
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:latest"
    hostname: redis
  
  springboot:
    container_name: springboot
    restart: always
    # Spring Boot 서버 설정
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p4886"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    depends_on:
      - my_mysql